'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pomodoro.Localization.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Public ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Italiano.
        '''</summary>
        Public ReadOnly Property Italian() As String
            Get
                Return ResourceManager.GetString("Italian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Languages.
        '''</summary>
        Public ReadOnly Property Languages() As String
            Get
                Return ResourceManager.GetString("Languages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minutes for long break.
        '''</summary>
        Public ReadOnly Property LongBreakIntervalInMin() As String
            Get
                Return ResourceManager.GetString("LongBreakIntervalInMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time for a longer break!.
        '''</summary>
        Public ReadOnly Property LongBreakMessage() As String
            Get
                Return ResourceManager.GetString("LongBreakMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Public ReadOnly Property Pause() As String
            Get
                Return ResourceManager.GetString("Pause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play.
        '''</summary>
        Public ReadOnly Property Play() As String
            Get
                Return ResourceManager.GetString("Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pomodoro.
        '''</summary>
        Public ReadOnly Property Pomodoro() As String
            Get
                Return ResourceManager.GetString("Pomodoro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferences.
        '''</summary>
        Public ReadOnly Property Preferences() As String
            Get
                Return ResourceManager.GetString("Preferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Public ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minutes for short break.
        '''</summary>
        Public ReadOnly Property ShortBreakIntervalInMin() As String
            Get
                Return ResourceManager.GetString("ShortBreakIntervalInMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Take a break!.
        '''</summary>
        Public ReadOnly Property ShortBreakMessage() As String
            Get
                Return ResourceManager.GetString("ShortBreakMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minutes for sitting.
        '''</summary>
        Public ReadOnly Property SitIntervalInMin() As String
            Get
                Return ResourceManager.GetString("SitIntervalInMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sit.
        '''</summary>
        Public ReadOnly Property SitMessage() As String
            Get
                Return ResourceManager.GetString("SitMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sit/Stand.
        '''</summary>
        Public ReadOnly Property SitStand() As String
            Get
                Return ResourceManager.GetString("SitStand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip forward.
        '''</summary>
        Public ReadOnly Property SkipFoward() As String
            Get
                Return ResourceManager.GetString("SkipFoward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minutes for standing.
        '''</summary>
        Public ReadOnly Property StandIntervalInMin() As String
            Get
                Return ResourceManager.GetString("StandIntervalInMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stand.
        '''</summary>
        Public ReadOnly Property StandMessage() As String
            Get
                Return ResourceManager.GetString("StandMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Public ReadOnly Property StopToolTip() As String
            Get
                Return ResourceManager.GetString("StopToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minutes for work.
        '''</summary>
        Public ReadOnly Property WorkIntervalInMin() As String
            Get
                Return ResourceManager.GetString("WorkIntervalInMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get to work....
        '''</summary>
        Public ReadOnly Property WorkMessage() As String
            Get
                Return ResourceManager.GetString("WorkMessage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
